apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
  labels:
    app: springboot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-k8s-deployment
    spec:
      containers:
        - name: springboot-k8s-deployment
          image: freeever/springboot-k8s-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
  labels:
    app: springboot-k8s-service
spec:
  ports:
    - nodePort: 31147
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-k8s-deployment
  type: NodePort
